```{r}
library(pacman)
p_load(
  MASS,
  here,
  rgdal,
  sf,
  terra,
  ggplot2,
  tmap,
  dplyr,
  gridExtra,
  cowplot,
  ggforce,
  concaveman,
  corrplot,
  tidyr,
  car,
  ggridges,
  ggcorrplot,
  ggfortify,
  lmtest,
  ggstats,
  tidymodels,
  themis,
  yardstick,
  MLmetrics,
  akima,
  olsrr,
  textrecipes,
  stopwords,
  tseries,
)
df <- read.csv(here("data", "listings.csv"))
```

```{r}
shape <- st_read(here("data", "SF Planning Neighborhood Groups Map"))
tmap_mode("plot")
```


```{r}
shape_plot <- shape %>% ggplot()+ geom_sf()
scatt<- shape_plot + 
  geom_point(data=df, aes(y=latitude, x=longitude), alpha=0.5, color="red", size=0.1)
groups <- 30
heatLog<- shape_plot + 
  stat_bin2d(data= df, aes(x=longitude, y=latitude), alpha=0.7, bins = groups, interpolate= T) +
  scale_fill_viridis_c(option="C", trans="log") +
  theme(legend.position = "none")
heat <- shape_plot + 
  stat_bin2d(
    data= df, 
    aes(x=longitude, y=latitude), 
    alpha=0.7, bins = groups, interpolate= T, linejoin="round"
    ) +
  scale_fill_viridis_c(option="C")
scatt
grid.arrange(heat, heatLog, ncol=2)
```

```{r}
df %>% filter(price > 0) -> df
grid <- interp(df$longitude, df$latitude, df$price, duplicate="ignore")
griddf <- data.frame(x = rep(grid$x, ncol(grid$z)), 
                     y = rep(grid$y, each = nrow(grid$z)), 
                     z = as.numeric(grid$z))
# ggplot(df, aes(x=longitude, y=latitude, z=price)) + geom_contour(aes(z=price))
ggplot(griddf,aes(x = x, y=y, z=z)) + geom_contour_filled()
ggplot(griddf,aes(x = x, y=y, z=z)) + geom_contour_filled()
```


```{r}
neighbourhoodss <- df %>%
  group_by(neighbourhood) %>%
  summarise(n = n()) %>%
  arrange(-n)
neighbourhoodss
neighbourhoodss %>% nrow()
```



```{r}
coloredScatt <- shape_plot +
  geom_point(data=df, aes(y=latitude, x=longitude, color=neighbourhood), alpha=0.5, size=0.1)
shape_plot +
  geom_mark_hull(data=df %>% filter(neighbourhood == c("Downtown/Civic Center", "South of Market", "Western Addition", "Mission")), aes(y=latitude, x=longitude, fill=neighbourhood), expand = 0, radius=0,alpha=0.7, size=0.1, level=0.2)
coloredScatt
```

```{r}
# price outliers
lower_limit <- quantile(df$price, 0.025)
upper_limit <- quantile(df$price, 0.975)

# há preços a 0
```


```{r}
pricePlot <- ggplot(data=df, aes(price))
pricebox <- pricePlot + 
  geom_boxplot() + 
  coord_flip()
pricebox # hard to visualize without xlim, but it becomes easier to see the high outliers
pricebox+ xlim(0, 500)
logPriceBox <- ggplot(data=df, aes(log(price)))
logPriceBox + geom_boxplot()
```



```{r}
priceHistPer20 <- pricePlot + # nota-se uma subida a cada +- 50$
  geom_histogram(binwidth=20, aes(y = ..density..)) +
  geom_density(color="red") +
  xlim(0, upper_limit)
priceHistPer50 <- pricePlot +
  geom_histogram(binwidth=50, aes(y = ..density..)) +
  geom_density(color="red") +
  xlim(0, upper_limit)
grid.arrange(priceHistPer20, priceHistPer50, ncol=2) 
```


```{r}
scattPriceMap <- shape_plot + 
  geom_point(
    data=df %>% filter(price < upper_limit),
    aes(y=latitude, x=longitude, color=price), alpha=0.5, size=0.5
  ) +
  scale_color_gradient(low="blue", high="red")
rasterPriceMap <- shape_plot +
  stat_summary_2d(
    data = df, 
    aes(y=latitude, x=longitude, z=price), binwidth=0.005, alpha = 0.8
    ) + 
  scale_fill_viridis_c(option="C", trans="log10") #log(average price
rasterLowerPriceMap <- shape_plot +
  stat_summary_2d(
    data = df %>% filter(price < upper_limit), 
    aes(y=latitude, x=longitude, z=price), binwidth=0.005, alpha = 0.8
    ) + 
  scale_fill_viridis_c(option="D") #non luxury average price

scattHighPriceMap <- shape_plot + 
  geom_point(
    data=df %>% filter(price >= upper_limit),
    aes(y=latitude, x=longitude, color=price), alpha=0.5, size=2, 
  ) +
  scale_color_gradient(low="#FF731D", high="#2A3990")
scattPriceMap
scattHighPriceMap
rasterLowerPriceMap
rasterPriceMap
df %>% arrange(latitude)
```

```{r}
ggplot(data = df, aes(x=price, y= neighbourhood, fill=neighbourhood)) + geom_density_ridges() + theme_ridges() + theme(legend.position = "none") + xlim(0, upper_limit)
df %>% ggplot(aes(y=price, x = forcats::fct_reorder(neighbourhood, price, .fun=median))) + geom_boxplot() + coord_cartesian(ylim=c(0, upper_limit)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r}
df %>% group_by(neighbourhood) %>% summarise(med = median(price))
```



```{r}
cheaperPricesScatt <- shape_plot + 
  geom_point(
    data=df %>% filter(price <= mean(df$price)),
    aes(y=latitude, x=longitude, color=price), alpha=0.5, size=0.5
  ) +
  scale_color_gradient(low="blue", high="red")
MoreExpNotLuxPricesScatt <- shape_plot + 
  geom_point(
    data=df %>% filter(price > mean(df$price) & price < upper_limit),
    aes(y=latitude, x=longitude, color=price), alpha=0.5, size=0.5
  ) +
  scale_color_gradient(low="blue", high="red")
cheaperPricesScatt
MoreExpNotLuxPricesScatt
```

```{r}
df %>%
  group_by(room_type) %>% 
  summarise(
    n = n(), 
    freq = n()/nrow(.),
    averagePrice = mean(price), 
    minPrice = min(price), 
    maxPrice = max(price)
  )
df %>% 
  group_by(neighbourhood) %>% 
  summarise(
    n = n(), 
    freq = n()/nrow(.),
    averagePrice = mean(price), 
    minPrice = min(price), 
    maxPrice = max(price)
  ) %>% arrange(-n)
df %>% 
  group_by(neighbourhood, room_type) %>%
  summarise(
    n = n(), 
    averagePrice = mean(price), 
    minPrice = min(price), 
    maxPrice = max(price)
  ) %>% 
  arrange(neighbourhood, room_type)
df %>% 
  group_by(neighbourhood, room_type) %>%
  summarise(
    n = n(), 
    averagePrice = mean(price), 
    minPrice = min(price), 
    maxPrice = max(price)
  ) %>% 
  arrange(-averagePrice)
df %>% 
  group_by(neighbourhood, room_type) %>%
  filter(price < upper_limit) %>%
  summarise(
    n = n(),
    averagePrice = mean(price), 
    minPrice = min(price), 
    maxPrice = max(price)
  ) %>% 
  arrange(-averagePrice)
```



```{r}
corrplot(df %>% select_if(is.numeric) %>% cor(), method="pie")
mean(df$price)
cor(df %>%
select(latitude, longitude,
price, reviews_per_month,
availability_365,
number_of_reviews_ltm))
df %>% filter(is.na(reviews_per_month))
corrplot(df %>% select_if(is.numeric) %>% cor(method= 'kendall'), method="pie")
```


```{r}
md1 <- lm(price ~ number_of_reviews + minimum_nights, df)
summary(md1)
mean(residuals(md1))
```

```{r}
md2 <- lm(reviews_per_month ~ number_of_reviews + minimum_nights, df)

```

```{r}
df2 <- df %>% select(price, minimum_nights, number_of_reviews, reviews_per_month, calculated_host_listings_count, number_of_reviews_ltm)

scatterplotMatrix(df2, smooth = FALSE, main="Scatter Plot Matrix")

```



```{r}
df %>% count(minimum_nights)
df %>% select(price, neighbourhood, latitude, longitude, room_type) %>%
  mutate(isLuxuary = price > quantile(df$price, 0.975) + 20, logPrice = log(price), )
df %>% arrange(-price) %>% select(name, price, host_name)
```


```{r}
# dummies
denseGroups <- df %>%
group_by(neighbourhood) %>%
summarise(n = n(), freq = n/nrow(df)) %>% 
arrange(-n) %>% mutate(ind = row_number(), cum = cumsum(freq), grouped = case_when(cum>0.66 ~ 1, cum <= 0.66 & cum >=0.33 ~ 2, TRUE ~ 3))
groupDensest <- denseGroups %>% filter(grouped==3)
groupLowDensity <- denseGroups %>% filter(grouped==1)  



df %>% filter(price > 0) %>%
  select(neighbourhood, latitude, longitude, room_type, price) %>%
  mutate(
    isFromDenseGroup = ifelse(neighbourhood %in% groupDensest$neighbourhood, 1, 0),
    isFromLowDenseGroup = ifelse(neighbourhood %in% groupLowDensity$neighbourhood, 1, 0),
    
    isInUpperPriceBracket = ifelse(neighbourhood %in% c('Diamond Heights','Potrero Hill','Castro/Upper Market','Glen Park','Russian Hill','Chinatown','Financial District','Marina','North Beach','Twin Peaks','Presidio'), 1, 0),
    isInLowerPriceBracket = ifelse(neighbourhood %in% c('Excelsior','Lakeshore','Crocker Amazon','Ocean View','Bayview','Visitacion Valley','Outer Sunset','Outer Mission','Parkside','Inner Sunset','Nob Hill','Mission','Downtown/Civic Center','West of Twin Peaks'), 1, 0),
    isPrivateRoom = ifelse(room_type == 'Private room', 1, 0),
    isSharedRoom = ifelse(room_type == 'Shared room', 1, 0),
    isHotel = ifelse(room_type == 'Hotel room', 1, 0),
  ) %>% select(-neighbourhood, -room_type) %>% relocate(price) %>% arrange(price) -> dfReady
dfReady
```

```{r}
#recipe testing
set.seed(2)

recipe <-recipe(price ~ neighbourhood + 
                  latitude + longitude + room_type + price + minimum_nights + number_of_reviews + calculated_host_listings_count + availability_365, data=df) %>%
  #step_tokenize(name) %>% 
  #step_stopwords(name) %>%
  #step_tokenfilter(name, max_tokens=30) %>%
  #step_tf(name) %>%
  step_upsample(room_type) %>%
  step_dummy(neighbourhood, room_type) %>% 
  prep()
dfSplit <- initial_split(df)
bake(recipe, training(dfSplit)) -> dfTraining
bake(recipe, testing(dfSplit)) -> dfTest
bake(recipe, df) -> dfAll
```

```{r}
testModel <- function (model){
  print("call")
  print(model$call)
  print("R^2")
  print(summary(model)$r.squared)
  print(bptest(model))
  print("standart residuals mean")
  print(mean(rstandard(model)))
  plot(model, 1)
  jarque.bera.test(model$residuals)
  print("MAPE = 0")
}
fit0 <- lm(price ~ ., dfAll)
fit1 <- lm(log10(price) ~ ., dfAll)
fit2 <- lm(1/price ~ ., dfAll)
testModel(fit0)
testModel(fit1)
testModel(fit2)
#fit2 é o melhor
```

```{r}
#crPlots(fit2)
```

```{r}
fit3 <- lm(1/price ~ ., dfAll %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3))
testModel(fit2)
testModel(fit3)
AIC(fit2, fit3)
```

```{r}
# pesos
fit4 <- lm(1/price ~ ., dfAll %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3), w=1/((1:nrow(dfAll))^2))
testModel(fit3)
testModel(fit4) #E(error) != 0?
AIC(fit3, fit4)
```

```{r}
fit5 <- lm(1/price ~ ., dfAll %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3), w=1/((1:nrow(dfAll))^0.5))
testModel(fit3)
testModel(fit5)
AIC(fit3, fit5)
```

```{r}
pfit3 <- predict(fit1, dfAll %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3))
fit6 <- lm(1/price ~ ., dfAll %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3), 
           w=(1/sqrt(pfit3)) + min(1/sqrt(pfit3)))
testModel(fit3)
testModel(fit6)
AIC(fit3, fit6)
```

```{r}
fit7 <- rlm(1/price ~ ., dfAll %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3))
testModel(fit3)
testModel(fit7)
AIC(fit3, fit7)
```

```{r}
h = 1/sqrt(fit3$residuals^2)
fit8 <-lm(1/price ~ .,dfAll %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3), w = h)
testModel(fit3)
testModel(fit8)
AIC(fit3, fit8)
#fit3 e fit8 são os melhores até agora
```


```{r}
MAPE(1/fit3$fitted.values,dfAll$price) # in-sample
fit3Training <- lm(1/price ~ ., dfTraining %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3))
predict(fit3Training, dfTest %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3)) -> p 
MLmetrics::MAPE(1/p, dfTest$price) #out of sample

MAPE(1/(fit8$fitted.values+ fit8$residuals), dfAll$price)# in-sample
h <- 1/sqrt(fit3Training$residuals^2)
fit8Training <-lm(1/price ~ .,dfTraining %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3), w = h)
predict(fit8Training, dfTest %>% mutate(minNightsSquared = minimum_nights^2, minNightsCube = minimum_nights^3)) -> p 
MLmetrics::MAPE(1/p, dfTest$price) #out of sample
```


```{r}
# corPlot
cor(dfReady) %>% ggcorrplot(lab=TRUE, type = "lower")
```

```{r}
dfSplit <- dfReady %>% group_initial_split()
```


```{r}
# apenas latitude e longitude

lm1 <- lm(price ~ .,data=dfReady %>% select(-logPrice))
lm1Log <- lm(logPrice ~ .,data=dfReady %>% select(-price))
summary(lm1Log)
h <- lm1Log$residuals^2


bestModel <- lm(logPrice ~ .,data=dfReady %>% select(-price), weights = 1/h)

bestModel %>% autoplot() -> temp
temp[[1]] #residuals vs fitted, pra ver a relacao linear (se n estiver funil? e a volta do 0)
dfReady %>% ggplot(aes(x=predict(bestModel), y=logPrice)) + geom_point()#alternativa
temp[[2]] #ve a normalidade de X, se for uma linha reta
hist(bestModel$residuals, breaks=seq(from=-2, to=3, by=0.1))#alternativa, visual
shapiro.test(sample(MASS::studres(bestModel),5000))#alternativa se p-value > 0.05
temp[[3]]#ve a homoscedascicity, se for uma linha horizontal e os pontos estão iguamnete espalhados
bptest# p < 0.05 H0 (homoskedasticity) é rejeitado e assume-se heteroskedasticity 
#temp[[4]]
#plot(bestModel, 4)

```


```{r}
shape_plot() +
  stat_summary_hex(data = df, aes(x=longitude, y=latitude, z= log(price)), alpha=0.8) +
  scale_fill_viridis_c() + 
```


























